language: cpp
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libssl-dev libcppunit-dev autotools-dev automake libpcre3-dev libxerces-c-dev pkg-config libgsm1-dev libspandsp-dev libspeexdsp-dev doxygen libopus-dev
compiler:
  - gcc
  - clang
script:
  - autoreconf -fi
  - ./configure --enable-topology-graph --disable-codec-ilbc --disable-codec-g726 --enable-codec-speex --enable-speex-dsp --enable-codec-g722 --enable-codec-opus --enable-codec-gsm
  - make -k
